### ISSUE TITLE
Git.io no longer accepting new links to shorten.

### ISSUE THREAD

**Issue by Krutoy242** [tanepiper/node-gitio#11]
This stated on https://git.io/

![image](https://user-images.githubusercontent.com/936618/150124055-a099c8d4-ddfd-4328-96e7-c473470e2797.png)

Please mark your [npm package](https://www.npmjs.com/package/gitio) as deprecated as its not working anymore 😔

Right now calling `gitio(...)` cause `Error: Internal Server Error`, so no functionality could be used.

**Comment by tanepiper** [comment]
@Krutoy242 Thanks - I've marked it as deprecated on NPM now and will updated this archive
