### ISSUE TITLE
Code option does not work

### ISSUE THREAD

**Issue by developit** [tanepiper/node-gitio#5]
Neither of these generate a URL with a custom code:

``` sh
gitio https://github.com/user/repo-name -c repo-name
gitio https://github.com/user/repo-name repo-name
```

**Comment by tanepiper** [comment]
@developit Can you check, does the repo already have a git.io shortened URL? I've seen issues where it won't generate another one if one has already been assigned

**Comment by tanepiper** [comment]
@developit Actually, looks like it might not work anymore: https://gist.github.com/defunkt/1209316

**Comment by developit** [comment]
@tanepiper It seems like the issue is that `node-gitio` isn't using `https`, which `git.io` just started enforcing last month.

**Comment by tanepiper** [comment]
@developit Hmm weird, as this is using the `https` library and has been for a while for doing requests.  

I've been re-factoring out the babel compile code (was a nice idea but with the import interop not coming for a while in node I'd rather it be clean and readable).  I'll have a look in to this at some point this week when I get time.
