### ISSUE TITLE
failed to create custom URL using this module, but sucseeded with curl

### ISSUE THREAD

**Issue by noformnocontent** [tanepiper/node-gitio#7]
## gitio
``` sh
gitio \
      https://github.com/noformnocontent/ru-phonetic-mac.klc/releases \
      ru-phonetic-mac.klc
```
> ** Error: The url https://github.com/noformnocontent/ru-phonetic-mac.klc/releases is not a valid address for git.io
>
> Shorten URLs like the cool kids
> gitio https://github.com/<path> [optional code]

## curl

``` sh
curl -i https://git.io \
     -F "url=https://github.com/noformnocontent/ru-phonetic-mac.klc/releases" \
     -F "code=ru-phonetic-mac.klc"
```
> HTTP/1.1 100 Continue
> 
> HTTP/1.1 201 Created
> Server: Cowboy
> Connection: keep-alive
> Date: Wed, 22 Mar 2017 19:04:55 GMT
> Status: 201 Created
> Content-Type: text/html;charset=utf-8
> Location: https://git.io/ru-phonetic-mac.klc
> Content-Length: 63
> X-Xss-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-Runtime: 0.120539
> X-Node: 1ea448f5-b0ec-4559-8ee1-c40461751ef6
> X-Revision: 4fdc60de6311e6a3aa31e19bc7b3aad7e85d33a6
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Via: 1.1 vegur
> 
> https://github.com/noformnocontent/ru-phonetic-mac.klc/releases%

**Comment by tanepiper** [comment]
Fixed in PR
